name: bomberos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.13
  firebase_auth: ^0.16.0
  permission_handler: ^5.0.0+hotfix.3
  google_fonts: ^1.0.0
  provider: ^4.0.5
  maps_launcher: ^1.2.0
  google_maps_flutter: ^0.5.27
  # google_maps_webservice: ^0.0.16
  shared_preferences: ^0.5.7
  agora_rtc_engine: ^1.0.10
  flutter_ringtone_player: ^2.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700